print(2 < 5)    # will print "True"
print(2 > 5)    # will print "False"
print(7 <= -1)  # will print "False"
print(6 >= 6)   # will print "True"
print(5 == 8)   # will print "False"
print(8 != 4)   # will print "True"
print(73 != 73) # will print "False"
print(2 == 2)   # will print "True"